
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-stack.fullname" . }}-mysql
  labels:
    app: mysql
    {{- include "wordpress-stack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app: mysql
    {{- include "wordpress-stack.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-stack.fullname" . }}-wordpress
  labels:
    app: wordpress
    {{- include "wordpress-stack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: wordpress
    {{- include "wordpress-stack.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-stack.fullname" . }}-nginx
  labels:
    app: nginx
    {{- include "wordpress-stack.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: metrics
      port: 9113
      targetPort: 9113
  selector:
    app: nginx
    {{- include "wordpress-stack.selectorLabels" . | nindent 4 }}

